log4j.logger.ros=INFO

log4j.logger.ros.move_base_flex=DEBUG
log4j.logger.ros.mbf_abstract_nav=DEBUG
log4j.logger.ros.mbf_gridmap_nav=DEBUG

log4j.logger.ros.mbf_gridmap_costmap_wrapper=DEBUG

log4j.logger.ros.teb_local_planner=DEBUG
# log4j.logger.ros.teb_local_planner.pluginlib=DEBUG

log4j.logger.ros.costmap_2d=DEBUG
# log4j.logger.ros.costmap_2d.pluginlib=DEBUG